### ISSUE TITLE
Bad mouse pointer position after setting a resolution in fullscreen

### ISSUE THREAD

**Issue by AsciiWolf** [stuntrally/stuntrally#30]
When using latest Stunt Rally from Git with OGRE 1.12.10, setting a different screen resolution ingame and switching to fullscreen, the actual mouse position is shifted and does not correspond with the mouse pointer position on screen. It gets fixed after restarting the game.

**Comment by cryham** [comment]
IDK if I can do anything about it. I wonder if this is something wrong in our code. Probably SDL window and Ogre/MyGui mouse cursor thing.
Is this a big difference, does it depend on resolution change or just constant offset of cursor size or something?

**Comment by AsciiWolf** [comment]
Hmm, on my laptop, the issue seems to happen only with 1920x1080 which is my native screen resolution.

**Comment by AsciiWolf** [comment]
Sometimes, this happens instead:
![screenshot](https://user-images.githubusercontent.com/2339930/111236550-6734e900-85f3-11eb-9650-2fad02853102.png)
(It seems that the new resolution is actually not applied, the old one is still used instead and game window is truncated.)

**Comment by AsciiWolf** [comment]
Anyway, it seems that the issue with new resolution not being correctly applied until restart also happens with older Stunt Rally 2.6.1 with old OGRE. But the cursor issue happens only on newer build that is using recent OGRE and much newer SDL. So yeah, it is probably a OGRE or SDL thing.

**Comment by cryham** [comment]
Hmm I just tested and in SR 2.6.1 with Ogre 1.9 on Debian 10:
- I don't have any issues changing resolution on fullscreen
- I saw this issue even after I changed to windowed from fullscreen, whole screen was drawn but main smaller resolution was shifted and drawn below while cursor was in fact above.
- After I restarted, now in windowed mode I don't have any issues changing resolution.
- I changed to fullscreen and saw this issue, well just wrong position of Quit button and GUI window size. After I changed resolution, it fixed itself.
Actually my both issues are fixed just by pressing resolution Change button.
Weird, but yeah I'd also assume SDL-OGRE issues, but perhaps something wrong in our logic.

**Comment by AsciiWolf** [comment]
Sadly still the same issue with latest Stunt Rally from Git (5ce6dde7273e61bf504e4b60bd288bfeac3a8ecb) + latest OGRE (13.4.4).

**Comment by cryham** [comment]
Thanks for testing. Please don't just bump topics. I guess nobody tried fixing it so it's still there. Not a critical issue for me, but yeah there are now many related to resolution change etc.

**Comment by cryham** [comment]
Strange, I don't have this on Debian with KDE.
Does it happen with `mouse_capture = on` and off too (in game.cfg)?
I guess this probably some new bug in `sdl4ogre/`. Maybe you could use `LogO(toStr(..) .. etc);` in `void SDLCursorManager::receiveCursorInfo(` or in `void BaseApp::onCursorChange(const string &name)` to log all those values there get some more info on what could be wrong. Just an idea, not sure if this is even it.
Honestly I'd rather throw out sdl4ogre and copy and use the code Ogre's sample browser has, also good for changing window and resolution.

**Comment by AsciiWolf** [comment]
Ugh, I just noticed that the resolution changing is quite glitchy. When fullscreen is already enabled, changing the resolution does not change it to a correct one. I first have to disable fullscreen, set the resolution, then restart the game and re-enable fullscreen. Weird.

**Comment by AsciiWolf** [comment]
Setting `mouse_capture` to `off` seems to have no effect.

Anyway, I have at least found a way to workaround this issue: When changing the resolution first, then enabling fullscreen (instead of first enabling fullscreen and changing the resolution afterwards), the issue does not happen.
